name: CI/CD Tienda Perritos - Backend ECS

on:
  push:
    branches:
      - main
    paths:
      - "backend/**"
      - ".github/workflows/**"

jobs:
  build-push-deploy-backend:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout codigo
        uses: actions/checkout@v4

      - name: Configurar credenciales AWS
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-session-token: ${{ secrets.AWS_SESSION_TOKEN }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Login Amazon ECR
        uses: aws-actions/amazon-ecr-login@v2

      - name: Build imagen Backend
        run: |
          cd backend
          docker build -t tienda-backend .

      - name: Tag imagen Backend
        run: |
          docker tag tienda-backend:latest ${{ secrets.ECR_REPO_URL_BACK }}:latest

      - name: Push imagen Backend a ECR
        run: |
          docker push ${{ secrets.ECR_REPO_URL_BACK }}:latest

      - name: Desplegar Backend en ECS
        run: |
          aws ecs update-service \
            --cluster tienda-perrito-cluster \
            --service Backend-Task-service \
            --force-new-deployment